# Smart Intercom project
# https://github.com/Artifan92/smart_domofon/

############# User configuration #############

substitutions:
  # Build configuration
  board_name: 'Domofon'
  mdns_name: 'domofon'
  build_path: 'domofon/'

  # Relays configuration
  phone_relay_inverted: 'true' # Set to 'false' if you have NO phone relay

  # Wifi credentials
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_ssid: 'domofon'
  ap_password: '1234567890'

  # OTA
  ota_password: 'esphome'

  # Software configuration
  call_start_detect_delay: 50ms # Wait a while before going into a ring state
  call_end_detect_delay: 4000ms # Interval between rings to detect incoming call
  short_click_time_from: 50ms # Short button click min time
  short_click_time_to: 1000ms # Long button click min time

########### End user configuration ###########

api:
  encryption:
    key: 'fjc2L+NtM/pLaDtBhW0nBxmErYBgQlwlRCfCduo6xs4='

packages:
  base: github://Artifan92/smart_domofon/packages/base.yaml@main
  api: github://Artifan92/smart_domofon/packages/api.yaml@main
  web_server: github://Artifan92/smart_domofon/packages/web_server.yaml@main
